name: Build (Windows)

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Setup build cache
        uses: pat-s/always-upload-cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup dependent native libraries
        run: |
          ./gradlew :downloadLibs
          cp libs/*.dll C:/Windows/
          ldd kosat-core/src/jvmTest/resources/lib/win64/*.dll

      - name: Build project using Gradle
        run: ./gradlew assemble --stacktrace --scan

      - name: Install drat-trim
        run: |
          git clone https://github.com/marijnheule/drat-trim
          cd drat-trim
          make drat-trim
          echo "$(realpath .)" >> $GITHUB_PATH

      - name: Run tests
        run: ./gradlew check --no-build-cache --stacktrace

      # Note: on Windows, you must stop the Gradle daemon at the end of CI process in order to release the lock on Gradle caches. Otherwise, cache-upload post-action step will fail, and your build cache won't be updated.
      - name: Stop Gradle daemon
        run: ./gradlew --stop
