name: Deploy site

on:
  push:
    branches: [main, feature/deploy]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Restore build cache
        uses: actions/cache/restore@v3
        id: restore-build-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project using Gradle
        run: ./gradlew build -x test -x jvmTest --stacktrace --scan

      - name: Deploy web app
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: kosat-web/build/dist
          target-folder: docs

      - name: Save build cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ steps.restore-build-cache.outputs.cache-primary-key }}
